CREATE TABLE IF NOT EXISTS EMPLOYEE (
      ROLL_NO TEXT PRIMARY KEY,
      NAME TEXT NOT NULL,
      ADDRESS TEXT,
      PHONE TEXT,
      AGE INTEGER

);

INSERT INTO EMPLOYEE (ROLL_NO , NAME,  ADDRESS, PHONE, AGE) VALUES

('1', 'RAM' , 'DELHI', '******' , 18),
('2', 'RAMESH' , 'GURGAON', '******' , 18),
('3', 'SUJIT' , 'ROHTAK', '******' , 20),
('4', 'SURESH' , 'DELHI', '******' , 18),
('5', 'AMAN' , 'ROHTAK', '******' , 20),
('6', 'HARSH' , 'GURGAON', '******' , 18);

SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE WHERE AGE = 20 AND ADDRESS = 'ROHTAK';

SELECT * FROM EMPLOYEE WHERE AGE = 18 AND NAME = 'RAM';

SELECT * FROM EMPLOYEE WHERE NAME = 'AMAN' OR NAME = 'SUJIT' ;

SELECT * FROM EMPLOYEE WHERE NAME = 'RAM' OR  AGE = 18;

SELECT * FROM EMPLOYEE WHERE AGE = 20 AND (NAME = 'AMAN' OR NAME = 'RAMESH');